name: Publish extension

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run vscode:prepublish
      - name: Runs on Pre-Release
        if: 'github.event.prerelease'
        run: npm run deploy-pre-release
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      - name: Runs on Release
        if: '!github.event.prerelease'
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}