# Github Action from: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
name: Extension Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'media/**'
      - 'resources/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'media/**'
      - 'resources/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Docker Image
      run: |
        docker pull materialize/materialized:v0.62.2
        docker run -d -v mzdata:/mzdata -p 6875:6875 -p 6876:6876 materialize/materialized:v0.62.2

    # They are only needed to test the action locally with `act`
    - name: Set up VSCode testing dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y libnss3-dev libasound2 libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libatk1.0-0

    - name: Run Tests on Linux
      if: runner.os == 'Linux'
      run: |
        export MZ_CONFIG_PATH=$HOME/.config/materialize/test
        xvfb-run -a npm test