# Github Action from: https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Run Docker Image
      run: |
        docker pull materialize/materialized:v0.62.2
        docker run -d -v mzdata:/mzdata -p 6875:6875 -p 6876:6876 materialize/materialized:v0.62.2

    - name: Setup config
      run: |
        mkdir -p /home/runner/.config/materialize
        echo "profile = 'test'" >> /home/runner/.config/materialize/mz.toml
        echo "[profiles.test]" >> /home/runner/.config/materialize/mz.toml
        echo "app-password = 'mzp_74b4cb1d805441d791b3132aaf82937571ac913400b94119a43e471516f2f0f0'" >> /home/runner/.config/materialize/mz.toml
        echo "region = 'aws/us-east-1'" >> /home/runner/.config/materialize/mz.toml
        echo "cloud-endpoint = 'http://localhost:3000'" >> /home/runner/.config/materialize/mz.toml
        echo "admin-endpoint = 'http://localhost:3000'" >> /home/runner/.config/materialize/mz.toml

    - run: npm install
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'